---
- name: Login to Docker Hub and push image
  hosts: all  # or specify your target hosts here if needed

  environment:
    DOCKER_USERNAME: "{{ gudurusanjay }}"
    DOCKER_PASSWORD: "{{ Sanjay@1927 }}"

  tasks:
    - name: TAG IMAGE WITH BUILD ID & LATEST
      shell: |
        cd /opt/docker
        docker build -t {{ project-1 }}:v1.{{ BUILD_ID }} .
        docker tag {{ project-1 }}:v1.{{ BUILD_ID }} SanjayGuduru/{{ project-1 }}:v1.{{ BUILD_ID }}
        docker tag {{ project-1 }}:v1.{{ BUILD_ID }} SanjayGuduru/{{ project-1 }}:latest

    - name: LOGIN DOCKERHUB & PUSH IMAGE ON REGISTRY
      shell: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push SanjayGuduru/{{ project-1 }}:v1.{{ BUILD_ID }}
        docker push SanjayGuduru/{{ project-1 }}:latest

    - name: REMOVE OLD IMAGES FROM SERVER
      shell: docker rmi -f $(docker images 'SanjayGuduru/{{ JOB_NAME }}' -a -q) &> /dev/null

    - name: LOGOUT DOCKERHUB
      shell: docker logout

