
- name: Tag Docker Image
  hosts: all
  become: yes
  tasks:
    - name: CREATE DOCKER DIRECTORY
      file:
        path: /opt/docker
        state: directory
        mode: '0755'

    - name: COPY FILES TO DOCKER DIRECTORY
      copy:
        src: /local/path/to/your/docker/files/
        dest: /opt/docker/
        owner: root
        group: root
        mode: '0755'

    - name: TAG IMAGE WITH BUILD ID & LATEST
      command: >
        bash -c "cd /opt/docker &&
        docker build -t project-1:v1.36 . &&
        docker tag project-1:v1.36 SanjayGuduru/project-1:v1.36 &&
        docker tag project-1:v1.36 SanjayGuduru/project-1:latest"

    - name: LOGIN TO DOCKERHUB
      command: echo "{{ gudurusanjay }}" | docker login -u "{{ gudurusanjay }}" --password-stdin
      vars:
        docker_username: "gudurusanjay"
        docker_password: "Sanjay@1927"

    - name: PUSH IMAGE TO DOCKERHUB
      command: >
        docker push SanjayGuduru/project-1:v1.36 &&
        docker push SanjayGuduru/project-1:latest
