---
- name: IMAGE PUSH
  hosts: all
  remote_user: root
  tasks:
    - name: TAG IMAGE WITH BUILD ID & LATEST
      shell: |
        cd /opt/docker
        docker build -t {{ project-1 }}:v1.{{ BUILD_ID }} .
        docker tag {{ project-1 }}:v1.{{ BUILD_ID }} gudurusanjay/{{ project-1 }}:v1.{{ BUILD_ID }}
        docker tag {{ project-1 }}:v1.{{ BUILD_ID }} gudurusanjay/{{ project-1 }}:latest

    - name: LOGIN DOCKERHUB & PUSH IMAGE ON REGISTRY
      shell: |        
        docker login -u {{ dockerhub_user }} -p {{ dockerhub_pass }}
        docker push gudurusanjay/{{ project-1 }}:v1.{{ BUILD_ID }}
        docker push gudurusanjay/{{ project-1 }}:latest

    - name: REMOVE OLD IMAGES FROM SERVER
      shell: docker rmi -f $(docker images 'gudurusanjay/{{ project-1 }}' -a -q) &> /dev/null

    - name: LOGOUT DOCKERHUB
      shell: docker logout
