---
- name: IMAGE PUSH
  hosts: all
  remote_user: root
  tasks:
    - name: TAG IMAGE WITH BUILD ID & LATEST
      shell: |
        cd /opt/docker
        docker build -t {{ JOB_NAME }}:v1.{{ BUILD_ID }} .
        docker tag {{ JOB_NAME }}:v1.{{ BUILD_ID }} gudurusanjay/{{ JOB_NAME }}:v1.{{ BUILD_ID }}
        docker tag {{ JOB_NAME }}:v1.{{ BUILD_ID }} gudurusanjay/{{ JOB_NAME }}:latest

    - name: LOGIN DOCKERHUB & PUSH IMAGE ON REGISTRY
      shell: |        
        docker login -u {{ gudurusanjay }} -p {{ Sanjay@1927 }}
        docker push gudurusanjay/{{ JOB_NAME }}:v1.{{ BUILD_ID }}
        docker push gudurusanjay/{{ JOB_NAME }}:latest

    - name: REMOVE OLD IMAGES FROM SERVER
      shell: docker rmi -f $(docker images 'gudurusanjay/{{ JOB_NAME }}' -a -q) &> /dev/null

    - name: LOGOUT DOCKERHUB
      shell: docker logout
