---
- name: Tag Docker Image and Push to Docker Hub
  hosts: all
  become: yes
  vars:
    project: "project-1"
    docker_username: "gudurusanjay"
    docker_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
      1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef

  tasks:
    - name: CREATE DOCKER DIRECTORY
      file:
        path: /opt/docker
        state: directory
        mode: '0755'

    - name: COPY FILES TO DOCKER DIRECTORY
      copy:
        src: /local/path/to/your/docker/files/
        dest: /opt/docker/
        owner: root
        group: root
        mode: '0755'

    - name: TAG IMAGE WITH BUILD ID & LATEST
      command: >
        bash -c "cd /opt/docker &&
        docker build -t {{ project }}:v1.36 . &&
        docker tag {{ project }}:v1.36 gudurusanjay/{{ project }}:v1.36 &&
        docker tag {{ project }}:v1.36 gudurusanjay/{{ project }}:latest"

    - name: LOGIN TO DOCKERHUB
      command: echo "{{ docker_password }}" | docker login -u "{{ docker_username }}" --password-stdin

    - name: PUSH IMAGE TO DOCKERHUB
      command: >
        docker push gudurusanjay/{{ project }}:v1.36 &&
        docker push gudurusanjay/{{ project }}:latest
