---
- name: Login to Docker Hub and push image
  ansible.builtin.shell:
    cmd: |
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker push SanjayGuduru/project-1:v1.52
      docker push SanjayGuduru/project-1:latest
  environment:
    DOCKER_USERNAME: gudurusanjay
    DOCKER_PASSWORD: Sanjay@1927

  tasks:
    - name: TAG IMAGE WITH BUILD ID & LATEST
      shell: |
        cd /opt/docker
        docker build -t {{ JOB_NAME }}:v1.{{ BUILD_ID }} .
        docker tag {{ JOB_NAME }}:v1.{{ BUILD_ID }} SanjayGuduru/{{ JOB_NAME }}:v1.{{ BUILD_ID }}
        docker tag {{ JOB_NAME }}:v1.{{ BUILD_ID }} SanjayGuduru/{{ JOB_NAME }}:latest

    - name: LOGIN DOCKERHUB & PUSH IMAGE ON REGISTRY
      shell: |        
        docker login -u {{ dockerhub_user }} -p {{ dockerhub_pass }}
        docker push SanjayGuduru/{{ JOB_NAME }}:v1.{{ BUILD_ID }}
        docker push SanjayGuduru/{{ JOB_NAME }}:latest

    - name: REMOVE OLD IMAGES FROM SERVER
      shell: docker rmi -f $(docker images 'gudurusanjay/{{ JOB_NAME }}' -a -q) &> /dev/null

    - name: LOGOUT DOCKERHUB
      shell: docker logout
